# Generated by Django 5.2.15 on 2026-07-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="host_moderation_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="blocked_from_rejoining",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="forced_muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="forced_video_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
