# Generated by Django 5.2.15 on 2026-07-10 07:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_meeting_host_moderation_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingPresenceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_sessions",
                        to="meetings.meetingparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
                "indexes": [
                    models.Index(
                        fields=["participant", "disconnected_at"],
                        name="meeting_presence_active_idx",
                    ),
                    models.Index(
                        fields=["last_seen_at"], name="meeting_presence_seen_idx"
                    ),
                ],
            },
        ),
    ]
