# Generated by Django 5.2.15 on 2026-08-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_meetingjoinrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="host_moderation_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
